name: hello-world
on: push
jobs: 
  my-job:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: set nodejs
          uses: actions/setup-node@v2
          with:
            node-version: '18'

        - name: Install dependencies
          run: npm install
        
        - name: run test
          run: |
            output=$(node dist/Test1.js)

            if [ "$output" -eq 0 ]; then
              echo "Test passed"
            else
              echo "Test failed"
              exit 1
            fi

